### POST request to example server
POST http://localhost:8081/patient/create-patient
Content-Type: application/json

{
  "name": "Ananya Reddy",
  "email": "ananya.reddy@gmail.com",
  "address": "Whitefield, Bangalore",
  "dob": "2001-11-08",
  "regestrationDate": "2026-09-02"
}
###