### POST request to example server
POST http://localhost:8081/patients/create-patient
Content-Type: application/json

{
  "name": "Rahul Sharma",
  "email": "rahul.sharma@gmail.com",
  "address": "Bangalore, Karnataka",
  "dob": "2003-05-15",
  "regestrationDate": "2026-08-25"
}


###