spring:
  application:
    name: analytics-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer