FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package


FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY --from=build ./app/target/billing-service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081
EXPOSE 9090

ENTRYPOINT ["java", "-jar", "app.jar"]